// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Queries.Persistence;

#nullable disable

namespace Queries.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240914143920_FluentApi")]
    partial class FluentApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Queries.Core.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("text");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("Integer");

                    b.Property<DateTime>("Released")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Queries.Core.Domain.Make", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7f26ac9-5b71-497f-b0a5-5c683e267181"),
                            Name = "Phillips"
                        },
                        new
                        {
                            Id = new Guid("b9c77744-3064-4d72-b349-ba12a23fecf7"),
                            Name = "Lego"
                        },
                        new
                        {
                            Id = new Guid("b4b83d92-d0ac-4bf9-8fae-8fe52284dd9a"),
                            Name = "Spil"
                        });
                });

            modelBuilder.Entity("Queries.Core.Domain.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MakeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42532caa-0a7f-4556-bcb2-43113ddb7386"),
                            MakeId = new Guid("b7f26ac9-5b71-497f-b0a5-5c683e267181"),
                            Name = "55OLED708"
                        },
                        new
                        {
                            Id = new Guid("acb956e0-7a1f-48c1-b100-7e9f35d9411b"),
                            MakeId = new Guid("b7f26ac9-5b71-497f-b0a5-5c683e267181"),
                            Name = "50PUS8079"
                        },
                        new
                        {
                            Id = new Guid("e0799875-c7cd-4c34-b119-9ce3d9f5f742"),
                            MakeId = new Guid("b7f26ac9-5b71-497f-b0a5-5c683e267181"),
                            Name = "48OLED708"
                        },
                        new
                        {
                            Id = new Guid("5f708c2e-5497-4b8f-a8e2-d393d7ef1540"),
                            MakeId = new Guid("b9c77744-3064-4d72-b349-ba12a23fecf7"),
                            Name = "Millennium Falcon"
                        },
                        new
                        {
                            Id = new Guid("c956850a-e488-420f-8611-dd30849aaa8e"),
                            MakeId = new Guid("b9c77744-3064-4d72-b349-ba12a23fecf7"),
                            Name = "R2-D2"
                        },
                        new
                        {
                            Id = new Guid("91414760-4cef-4da4-8c91-00e2b18078b2"),
                            MakeId = new Guid("b9c77744-3064-4d72-b349-ba12a23fecf7"),
                            Name = "AT-AT"
                        },
                        new
                        {
                            Id = new Guid("e5c7929a-956d-4e29-9b86-22f472430933"),
                            MakeId = new Guid("b4b83d92-d0ac-4bf9-8fae-8fe52284dd9a"),
                            Name = "Read dead redemption"
                        },
                        new
                        {
                            Id = new Guid("c06435a9-1913-4a52-a415-01c93753c388"),
                            MakeId = new Guid("b4b83d92-d0ac-4bf9-8fae-8fe52284dd9a"),
                            Name = "Call of duty"
                        },
                        new
                        {
                            Id = new Guid("c2dc45ee-9bb0-42e9-b625-aeddc53da952"),
                            MakeId = new Guid("b4b83d92-d0ac-4bf9-8fae-8fe52284dd9a"),
                            Name = "Counter strike 2"
                        });
                });

            modelBuilder.Entity("Queries.Core.Domain.Item", b =>
                {
                    b.HasOne("Queries.Core.Domain.Model", "Model")
                        .WithMany("Items")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Queries.Core.Domain.Model", b =>
                {
                    b.HasOne("Queries.Core.Domain.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("Queries.Core.Domain.Make", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Queries.Core.Domain.Model", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
